# Generated by Django 5.2.1 on 2025-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('products', 'Products & Services'), ('gallery', 'Gallery'), ('contact', 'Contact')], max_length=50)),
                ('section', models.CharField(max_length=100)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('color', 'Color')], max_length=20)),
                ('content_value', models.TextField()),
            ],
        ),
    ]
