# Generated by Django 5.2.1 on 2025-05-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('products', 'Products'), ('gallery', 'Gallery'), ('contact', 'Contact')], max_length=50)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('color', 'Color')], max_length=10)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
    ]
