# Generated by Django 5.2.1 on 2025-05-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitecontent_delete_pagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('color', 'Color'), ('map', 'Map')], max_length=10),
        ),
    ]
