# Generated by Django 5.2.1 on 2025-05-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitecontent_map_url_alter_sitecontent_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('navbar', 'Navbar'), ('home', 'Home'), ('about', 'About'), ('gallery', 'Gallery'), ('products', 'Products'), ('contact', 'Contact'), ('footer', 'Footer')], max_length=20)),
                ('image', models.ImageField(upload_to='backgrounds/')),
            ],
        ),
    ]
